---
source: src/validation/tests/array_validation_test.rs
expression: res
---
SemanticError { message: "Array __main_arr_init has size 5, but 6 were provided", range: [SourceRange { range: 102..106 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr has size 5, but 6 were provided", range: [SourceRange { range: 130..134 }], err_no: arr__invalid_array_assignment }

